name: turbidity-duero-river

on:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  scrapping:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2

    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("stringr")'
        R -e 'install.packages("devtools")'
        R -e 'devtools::install_github("hadley/rvest")'
        R -e 'install.packages("lubridate")'


    - name: scrape
      run: Rscript 'R/00_prepare.R'

    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add '*'
        git commit -am "water-quality get duero data: $(date)"
        git push origin main

    - name: Retry Step
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 1
        max_attempts: 3
        command: Rscript 'R/00_prepare.R'

      env:
        REPO_KEY: ${{github.token}}
        username: github-actions

